name: ErminePlugin
main: jcdc.pluginfactory.ermine.ErminePlugin
author: Josh Cough
version: 0.1.0
database: false
depend: [ScalaLibPlugin, ScalaPluginAPI, ErmineLibPlugin]
commands:
  runErmine:
    description: Run some ermine function
    usage: /runErmine module function args...